-- CreateTable
CREATE TABLE "Entry" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "red" INTEGER NOT NULL,
    "black" INTEGER NOT NULL,
    "win" BOOLEAN NOT NULL
);
